---
title: "Corona-Inzidenzen im Bundesländervergleich"
#output: html_document
---
```{r message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(tidyverse)
library(ggiraph)
library(stringi)
library(RColorBrewer)
library(viridis)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
map_germany_2 <- sf::read_sf("Deutschland Mapping Daten 2/")
corona_cases <- read_csv("https://opendata.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0.csv", guess_max = 2500000)
bundeslaender_cases <- corona_cases %>%
  group_by(Bundesland, Meldedatum) %>%
  summarise(cases = sum(AnzahlFall)) %>%
  mutate(Meldedatum = as.Date(Meldedatum))

write_rds(bundeslaender_cases, "Deutschland Mapping Daten 2/cases.rds")
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
map_germany_final <- map_germany_2[-c(17, 18, 19, 20, 21, 22), ]
		names(map_germany_final)[names(map_germany_final) == 'NUTS_NAME'] <- 'Bundesland'
		
map_germany_final %>%
  mutate(linkname = str_to_lower(str_remove_all(Bundesland, "[äüö ()ß.]"))) %>%
		mutate(jscode = glue::glue('window.location.href = "{linkname}.html";')) %>%
		left_join(bundeslaender_cases %>% filter(Meldedatum == "2021-08-15"), 
		by = c("Bundesland" = "Bundesland")) %>%
		  
    ggplot() +
		aes(fill = cases) +
		geom_sf_interactive(aes(tooltip = cases, onclick = jscode)) + 
    labs(title = "Die meisten Corona-Infektionen Mitte\nAugust hat NRW gemeldet. In den östlichen\nBundesländern traten vergleichsweise\nwenige Fälle auf.",
              subtitle = "Anzahl gemeldeter Corona-Fälle nach Bundesland",
              caption = "Quelle: RKI") +
    scale_fill_viridis_c(option = "magma", direction=-1) + 
    theme_bw() -> corona_map_germany_2
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
ggiraph::girafe(
		ggobj = corona_map_germany_2, pointsize = 14, width_svg = 6, height_svg = 6 * 0.618
		)
```
